planner:
  epsilon: 100
  name: ARA
  verbose: true
  use_dijkstra_heuristic: true
  use_uniform_obstacle_cost: false
  use_multiresolution_motion_primitives: true
  research:
    solve_with_ik_threshold: 0.02
    sum_heuristics: false
    short_distance_mprims_threshold: 0.2
  rstar:
    random_seed: -1
    number_random_successors: 30
    random_successor_distance: 0.2
  
robot:
  arm_name: right_arm
  num_joints: 7
  
debug:
  print_out_path: false

visualizations:
  heuristic: false
  goal: true
  expanded_states: false
  trajectory: true
  collision_model_trajectory: false
  trajectory_throttle: 5

collision_space:
  reference_frame: base_link
  resolution: 0.01
  lowres_cc: true
  collision_map_topic: collision_map_occ
  collision_checking_resolution: 0.02

  occupancy_grid:
    origin_x: -0.6
    origin_y: -1.25
    origin_z: -0.05
    size_x: 1.6
    size_y: 1.6
    size_z: 1.4

reference_frame: base_link
FK_service_name: pr2_right_arm_kinematics/get_fk
IK_service_name: pr2_right_arm_kinematics/get_ik


