planner:
  epsilon: 100
  name: ARA
  verbose: true
  use_dijkstra_heuristic: true
  use_research_heuristic: false
  use_uniform_obstacle_cost: false
  use_multiresolution_motion_primitives: true
  research:
    solve_with_ik_threshold: 0.1
    sum_heuristics: false
    short_distance_mprims_threshold: 0.2
  
robot:
  arm_name: right_arm
  num_joints: 7
  
debug:
  print_out_path: true

visualizations:
  heuristic: false
  goal: true
  expanded_states: false
  trajectory: true
  collision_model_trajectory: false
  trajectory_throttle: 5

collision_space:
  reference_frame: base_link
  resolution: 0.02
  collision_map_topic: collision_map_occ

  occupancy_grid:
    origin_x: -0.6
    origin_y: -1.25
    origin_z: -0.05
    size_x: 1.8
    size_y: 1.8
    size_z: 1.8

reference_frame: base_link
FK_service_name: pr2_right_arm_kinematics/get_fk
IK_service_name: pr2_right_arm_kinematics/get_ik


